import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  ShadingType,
  convertInchesToTwip,
} from 'docx';
import { getDiscussionQuestions, extractKeyVocabulary } from './templates';
import type { TeachingMaterialInput } from './types';

function getStrings(locale: string) {
  if (locale === 'ja') {
    return {
      teacherNotes: '講師用レッスンプラン',
      sessionOverview: 'セッション概要',
      date: '日付',
      duration: '時間',
      format: '形式',
      instructor: '講師',
      description: '説明',
      materialsNeeded: '必要な教材・ツール',
      topicBreakdown: 'トピック詳細',
      suggestedTime: '推奨時間',
      keyPoints: '重要ポイント',
      discussionQuestions: 'ディスカッション・クエスチョン',
      keyVocabulary: 'キーボキャブラリー',
      resourcesAndMaterials: 'リソース・教材',
      slideDeck: 'スライドデッキ',
      personalNotes: 'あなたのメモ',
      personalNotesPlaceholder: 'ここに自分のメモや準備内容を追記してください...',
      minutes: (n: number) => `約${n}分`,
      session: (n: number) => `セッション${n}`,
      generatedBy: 'HonuVibe.AIが自動生成',
      noDescription: '説明なし',
    };
  }
  return {
    teacherNotes: "Teacher's Lesson Plan",
    sessionOverview: 'Session Overview',
    date: 'Date',
    duration: 'Duration',
    format: 'Format',
    instructor: 'Instructor',
    description: 'Description',
    materialsNeeded: 'Materials & Tools Needed',
    topicBreakdown: 'Topic Breakdown',
    suggestedTime: 'Suggested Time',
    keyPoints: 'Key Points',
    discussionQuestions: 'Discussion Questions',
    keyVocabulary: 'Key Vocabulary',
    resourcesAndMaterials: 'Resources & Materials',
    slideDeck: 'Slide Deck',
    personalNotes: 'Your Notes',
    personalNotesPlaceholder: 'Add your own notes and preparation content here...',
    minutes: (n: number) => `~${n} min`,
    session: (n: number) => `Session ${n}`,
    generatedBy: 'Auto-generated by HonuVibe.AI',
    noDescription: 'No description available',
  };
}

// Brand colors
const TEAL_HEX = '2DD4BF';
const DARK_BG_HEX = '1A1F2E';
const LIGHT_BG_HEX = 'F8FAFC';
const BORDER_HEX = 'E2E8F0';

function metaCell(label: string, value: string): TableCell {
  return new TableCell({
    width: { size: 50, type: WidthType.PERCENTAGE },
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: BORDER_HEX },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: BORDER_HEX },
      left: { style: BorderStyle.SINGLE, size: 1, color: BORDER_HEX },
      right: { style: BorderStyle.SINGLE, size: 1, color: BORDER_HEX },
    },
    children: [
      new Paragraph({
        spacing: { after: 40 },
        children: [
          new TextRun({ text: label, size: 16, color: '94A3B8', bold: true }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: value, size: 20, color: '334155' }),
        ],
      }),
    ],
  });
}

export async function generateTeacherNotes(input: TeachingMaterialInput): Promise<Buffer> {
  const s = getStrings(input.locale);
  const topicCount = input.topics.length || 1;
  const timePerTopic = input.sessionDuration
    ? Math.floor(input.sessionDuration / topicCount)
    : null;

  const formattedDate = input.scheduledAt
    ? new Date(input.scheduledAt).toLocaleDateString(
        input.locale === 'ja' ? 'ja-JP' : 'en-US',
        { year: 'numeric', month: 'long', day: 'numeric' },
      )
    : '—';

  const sections: Paragraph[] = [];

  // --- Header ---
  sections.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      spacing: { after: 80 },
      children: [
        new TextRun({
          text: `${s.session(input.sessionNumber)}: ${input.sessionTitle}`,
          bold: true,
          size: 36,
          color: DARK_BG_HEX,
        }),
      ],
    }),
    new Paragraph({
      spacing: { after: 200 },
      children: [
        new TextRun({ text: input.courseName, size: 22, color: '64748B' }),
        input.courseCode
          ? new TextRun({ text: ` (${input.courseCode})`, size: 22, color: '94A3B8' })
          : new TextRun({ text: '' }),
      ],
    }),
  );

  // --- Session Overview Meta Table ---
  sections.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 240, after: 120 },
      children: [
        new TextRun({ text: s.sessionOverview, bold: true, size: 28, color: DARK_BG_HEX }),
      ],
    }),
  );

  const metaTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          metaCell(s.instructor, input.instructorName),
          metaCell(s.date, formattedDate),
        ],
      }),
      new TableRow({
        children: [
          metaCell(s.duration, input.sessionDuration ? `${input.sessionDuration} min` : '—'),
          metaCell(s.format, input.sessionFormat),
        ],
      }),
    ],
  });
  // Table needs to be added to a section in the document, we handle it below

  // Description
  const descParagraph = new Paragraph({
    spacing: { before: 160, after: 120 },
    children: [
      new TextRun({
        text: input.description || s.noDescription,
        size: 20,
        color: '64748B',
        italics: !input.description,
      }),
    ],
  });

  // --- Materials ---
  const materialParagraphs: Paragraph[] = [];
  if (input.materials.length > 0) {
    materialParagraphs.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 240, after: 120 },
        children: [
          new TextRun({ text: s.materialsNeeded, bold: true, size: 28, color: DARK_BG_HEX }),
        ],
      }),
    );
    for (const mat of input.materials) {
      materialParagraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 60 },
          children: [new TextRun({ text: mat, size: 20 })],
        }),
      );
    }
  }

  // --- Topic Breakdown ---
  const topicParagraphs: Paragraph[] = [];
  topicParagraphs.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 280, after: 120 },
      children: [
        new TextRun({ text: s.topicBreakdown, bold: true, size: 28, color: DARK_BG_HEX }),
      ],
    }),
  );

  for (let i = 0; i < input.topics.length; i++) {
    const topic = input.topics[i];

    // Topic heading
    topicParagraphs.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 200, after: 80 },
        children: [
          new TextRun({
            text: `${i + 1}. ${topic.title}`,
            bold: true,
            size: 24,
            color: DARK_BG_HEX,
          }),
        ],
      }),
    );

    // Suggested time
    if (timePerTopic) {
      topicParagraphs.push(
        new Paragraph({
          spacing: { after: 80 },
          children: [
            new TextRun({ text: `${s.suggestedTime}: `, bold: true, size: 18, color: '64748B' }),
            new TextRun({ text: s.minutes(timePerTopic), size: 18, color: TEAL_HEX }),
          ],
        }),
      );
    }

    // Key points (subtopics)
    if (topic.subtopics.length > 0) {
      topicParagraphs.push(
        new Paragraph({
          spacing: { before: 80, after: 60 },
          children: [
            new TextRun({ text: s.keyPoints, bold: true, size: 18, color: '334155' }),
          ],
        }),
      );
      for (const sub of topic.subtopics) {
        topicParagraphs.push(
          new Paragraph({
            bullet: { level: 0 },
            spacing: { after: 40 },
            children: [new TextRun({ text: sub, size: 20 })],
          }),
        );
      }
    }

    // Discussion questions
    const questions = getDiscussionQuestions(topic.title, topic.subtopics, i, input.locale);
    topicParagraphs.push(
      new Paragraph({
        spacing: { before: 120, after: 60 },
        children: [
          new TextRun({ text: s.discussionQuestions, bold: true, size: 18, color: TEAL_HEX }),
        ],
      }),
    );
    for (const q of questions) {
      topicParagraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 40 },
          children: [new TextRun({ text: q, size: 18, italics: true, color: '64748B' })],
        }),
      );
    }
  }

  // --- Key Vocabulary ---
  const vocab = extractKeyVocabulary(input.topics);
  const vocabParagraphs: Paragraph[] = [];
  if (vocab.length > 0) {
    vocabParagraphs.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 240, after: 120 },
        children: [
          new TextRun({ text: s.keyVocabulary, bold: true, size: 28, color: DARK_BG_HEX }),
        ],
      }),
    );
    for (const term of vocab) {
      vocabParagraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 40 },
          children: [new TextRun({ text: term, size: 20, bold: true })],
        }),
      );
    }
  }

  // --- Resources ---
  const resourceParagraphs: Paragraph[] = [];
  const hasResources = input.resources.length > 0 || input.slideDeckUrl;
  if (hasResources) {
    resourceParagraphs.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 240, after: 120 },
        children: [
          new TextRun({ text: s.resourcesAndMaterials, bold: true, size: 28, color: DARK_BG_HEX }),
        ],
      }),
    );
    if (input.slideDeckUrl) {
      resourceParagraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 40 },
          children: [
            new TextRun({ text: `${s.slideDeck}: `, bold: true, size: 20 }),
            new TextRun({ text: input.slideDeckUrl, size: 20, color: TEAL_HEX }),
          ],
        }),
      );
    }
    for (const res of input.resources) {
      const resTitle = input.locale === 'ja' && res.title_jp ? res.title_jp : res.title_en;
      resourceParagraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 40 },
          children: [
            new TextRun({ text: resTitle, size: 20, bold: true }),
            res.url ? new TextRun({ text: ` — ${res.url}`, size: 18, color: TEAL_HEX }) : new TextRun({ text: '' }),
          ],
        }),
      );
    }
  }

  // --- Personal Notes Section ---
  const notesParagraphs: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 280, after: 120 },
      children: [
        new TextRun({ text: s.personalNotes, bold: true, size: 28, color: DARK_BG_HEX }),
      ],
    }),
    new Paragraph({
      spacing: { after: 80 },
      shading: { type: ShadingType.SOLID, color: LIGHT_BG_HEX, fill: LIGHT_BG_HEX },
      children: [
        new TextRun({
          text: s.personalNotesPlaceholder,
          size: 18,
          italics: true,
          color: '94A3B8',
        }),
      ],
    }),
    // Blank lines for writing
    ...Array.from({ length: 12 }, () =>
      new Paragraph({
        spacing: { after: 200 },
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 1, color: BORDER_HEX },
        },
        children: [new TextRun({ text: ' ', size: 20 })],
      }),
    ),
  ];

  // --- Footer ---
  const footerParagraph = new Paragraph({
    spacing: { before: 240 },
    alignment: AlignmentType.CENTER,
    children: [
      new TextRun({ text: s.generatedBy, size: 16, color: '94A3B8', italics: true }),
    ],
  });

  // --- Build Document ---
  const doc = new Document({
    styles: {
      default: {
        document: {
          run: {
            font: input.locale === 'ja' ? 'Noto Sans JP' : 'Calibri',
            size: 20,
          },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
              right: convertInchesToTwip(1),
            },
          },
        },
        children: [
          ...sections,
          metaTable,
          descParagraph,
          ...materialParagraphs,
          ...topicParagraphs,
          ...vocabParagraphs,
          ...resourceParagraphs,
          ...notesParagraphs,
          footerParagraph,
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}
