// Questionnaire chrome copy — the inline `const T = { en, ja }` convention from
// components/survey/SurveyForm.tsx, lifted into one module because five
// components share it. The JA strings ship FLAGGED FOR NATIVE REVIEW per
// CLAUDE.md (no unreviewed machine translation in production); see the ship
// report. Question content itself comes from the questionnaire manifest,
// already in the client's language.

export const T = {
  en: {
    brand: 'HonuVibe Studio',
    eyebrow: 'Discovery questionnaire',
    autosaveHint: 'Your answers save automatically — you can close this tab and come back anytime.',
    required: 'Required',
    optional: 'Optional',
    other: 'Other',
    otherPlaceholder: 'Tell us more…',
    chooseUpTo: (n: number) => `Choose up to ${n}.`,
    charsLeft: (n: number) => `${n} characters left`,
    sectionOf: (i: number, n: number) => `Section ${i} of ${n}`,
    prev: 'Previous',
    next: 'Next section',
    submit: 'Submit answers',
    submitting: 'Submitting…',
    saving: 'Saving…',
    saved: 'Saved',
    savedAgo: (label: string) => `Saved · ${label}`,
    justNow: 'just now',
    minAgo: (n: number) => `${n} min ago`,
    hoursAgo: (n: number) => `${n} h ago`,
    unsaved: 'Unsaved — retry',
    offline: 'Offline — will retry',
    retry: 'Retry',
    unsavedBlock: 'Some answers have not been saved yet. Retry, then submit.',
    requiredMissing: 'This question is required.',
    missingIntro: (n: number) => (n === 1 ? 'One required question is still blank.' : `${n} required questions are still blank.`),
    pickAtLeastOne: 'Please choose at least one.',
    submitFailed: 'Something went wrong while submitting. Your answers are saved — please try again.',
    briefInFlight: 'We are still processing your previous submission. Your answers are saved — please try again in a minute or two.',
    thanksTitle: 'Thank you — all received.',
    thanksBody: "Ryan will read through your answers before the discovery call. If you think of anything else, just reply to the email you received.",
    readOnlyNote: 'You submitted this questionnaire. Your answers are shown below for reference.',
    submittedOn: (date: string) => `Submitted ${date}`,
    forbiddenTitle: 'This link needs to be opened from your email again',
    forbiddenBody: 'Your browser is not holding the key for this questionnaire — that happens after clearing cookies, switching browsers, or if the link was revoked. Open the newest link from your email, or reply to it and Ryan will send a fresh one.',
    expiredTitle: 'This link has expired',
    expiredBody: 'Reply to the email you received and Ryan will send you a new link. Any answers you already saved are safe.',
    staleTitle: 'This questionnaire was updated',
    staleBody: 'Reloading to fetch the latest version…',
    unavailableTitle: 'Temporarily unavailable',
    unavailableBody: 'Please try again in a few minutes.',
    leaveWarning: 'Some answers are still saving.',
    answered: (a: number, n: number) => `${a} of ${n} answered`,
    beforeSubmitNote: 'Take your time — nothing is sent to Ryan until you press Submit.',
  },
  ja: {
    brand: 'HonuVibe Studio',
    eyebrow: 'ディスカバリー・アンケート',
    autosaveHint: '回答は自動的に保存されます。タブを閉じても、いつでも同じリンクから再開できます。',
    required: '必須',
    optional: '任意',
    other: 'その他',
    otherPlaceholder: '具体的に教えてください…',
    chooseUpTo: (n: number) => `最大${n}つまで選択できます。`,
    charsLeft: (n: number) => `残り${n}文字`,
    sectionOf: (i: number, n: number) => `セクション ${i} / ${n}`,
    prev: '前へ',
    next: '次のセクション',
    submit: '回答を送信する',
    submitting: '送信中…',
    saving: '保存中…',
    saved: '保存済み',
    savedAgo: (label: string) => `保存済み · ${label}`,
    justNow: 'たった今',
    minAgo: (n: number) => `${n}分前`,
    hoursAgo: (n: number) => `${n}時間前`,
    unsaved: '未保存 — 再試行',
    offline: 'オフライン — 再試行します',
    retry: '再試行',
    unsavedBlock: 'まだ保存されていない回答があります。再試行してから送信してください。',
    requiredMissing: 'この質問は必須です。',
    missingIntro: (n: number) => `必須の質問が${n}件未回答です。`,
    pickAtLeastOne: '1つ以上選択してください。',
    submitFailed: '送信中に問題が発生しました。回答は保存されていますので、もう一度お試しください。',
    briefInFlight: '前回の送信を処理中です。回答は保存されていますので、1〜2分後にもう一度お試しください。',
    thanksTitle: 'ありがとうございます。すべて受け取りました。',
    thanksBody: 'ディスカバリーのお打ち合わせの前に、Ryanがご回答に目を通します。追加でお伝えしたいことがあれば、届いたメールにそのまま返信してください。',
    readOnlyNote: 'このアンケートは送信済みです。ご回答を以下に表示しています。',
    submittedOn: (date: string) => `${date} に送信`,
    forbiddenTitle: 'メールのリンクからもう一度開いてください',
    forbiddenBody: 'このブラウザにアンケートの鍵が保存されていません。Cookieの削除やブラウザの変更、またはリンクが無効化された場合に起こります。メールに届いた最新のリンクを開くか、メールに返信していただければ新しいリンクをお送りします。',
    expiredTitle: 'このリンクは期限切れです',
    expiredBody: '届いたメールに返信していただければ、新しいリンクをお送りします。保存済みの回答はそのまま残っています。',
    staleTitle: 'アンケートが更新されました',
    staleBody: '最新の内容を読み込んでいます…',
    unavailableTitle: '一時的にご利用いただけません',
    unavailableBody: '数分後にもう一度お試しください。',
    leaveWarning: 'まだ保存中の回答があります。',
    answered: (a: number, n: number) => `${n}問中${a}問回答済み`,
    beforeSubmitNote: '「回答を送信する」を押すまで、Ryanには何も送られません。ゆっくりご記入ください。',
  },
};

export type Copy = (typeof T)['en'];
